import Head from 'next/head'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import {SliderData} from '../components/SliderData.js'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo's Catagory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Vvolf' message ='I hacked the best security systems in the world.' />
      <Slider slides={SliderData}/>
      <Footer/>

    </div>
  )
}
